import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.sqlDelight)
    alias(libs.plugins.metro)
    alias(libs.plugins.structured.coroutines)
    alias(libs.plugins.stability.analyzer)
    alias(libs.plugins.aboutLibraries)
}

/**
 * Writes the Google OAuth client into a generated source file so it never lives in git.
 *
 * Local builds read `oauth.local.properties` at the repository root; CI reads the same names from the
 * environment. A missing value still compiles - that provider is then simply not offered in the UI.
 */
abstract class GenerateOAuthSecrets : DefaultTask() {
    /** Constant name -> value, e.g. GOOGLE_CLIENT_ID -> "123.apps.googleusercontent.com". */
    @get:Input
    abstract val values: MapProperty<String, String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        fun esc(value: String) = value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        val dir = outputDir.get().asFile.resolve("co/abaye/mailtice/auth")
        dir.mkdirs()
        dir.resolve("OAuthSecrets.kt").writeText(
            """
            |// Generated by :shared:generateOAuthSecrets - do not edit, do not commit.
            |package co.abaye.mailtice.auth
            |
            |internal object OAuthSecrets {
            |${values.get().entries.sortedBy { it.key }.joinToString("\n") { (k, v) -> "    const val $k: String = \"${esc(v)}\"" }}
            |}
            |
            """.trimMargin(),
        )
    }
}

val oauthFile = providers.fileContents(rootProject.layout.projectDirectory.file("oauth.local.properties")).asText

fun oauthValue(key: String): Provider<String> = providers.environmentVariable(key)
    .orElse(oauthFile.map { text -> Properties().apply { load(text.reader()) }.getProperty(key).orEmpty() })
    .orElse("")

val oauthKeys = listOf(
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "GOOGLE_WEB_CLIENT_ID",
    "GOOGLE_WEB_CLIENT_SECRET",
    "MICROSOFT_CLIENT_ID",
    "YAHOO_CLIENT_ID",
    "YAHOO_CLIENT_SECRET",
    "YAHOO_REDIRECT_URI",
)

val generateOAuthSecrets = tasks.register<GenerateOAuthSecrets>("generateOAuthSecrets") {
    oauthKeys.forEach { key -> values.put(key, oauthValue(key)) }
    outputDir.set(layout.buildDirectory.dir("generated/oauth/kotlin"))
}

kotlin {
    android {
        namespace = "co.abaye.mailtice.shared"
        // 37 is a floor: materialKolor, aboutlibraries and the AndroidX Compose artifacts demand it.
        compileSdk = 37
        minSdk = 26
        androidResources.enable = true
        compilerOptions { jvmTarget = JvmTarget.JVM_17 }
    }

    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    sourceSets {
        // Desktop and Android are both JVMs: the IMAP stack (Angus Mail) and everything built on
        // it lives once, here, instead of twice.
        val jvmSharedMain = create("jvmSharedMain") {
            dependsOn(commonMain.get())
        }
        jvmMain.get().dependsOn(jvmSharedMain)
        androidMain.get().dependsOn(jvmSharedMain)

        jvmSharedMain.dependencies {
            implementation(libs.jakarta.mail.api)
            implementation(libs.angus.mail)
            implementation(libs.angus.activation)
        }

        commonMain.configure {
            kotlin.srcDir(generateOAuthSecrets.flatMap { it.outputDir })
        }

        commonMain.dependencies {
            api(libs.compose.runtime)
            api(libs.compose.ui)
            api(libs.compose.foundation)
            api(libs.compose.resources)
            // Hebrew calendar and sunset times (KosherJava ported to Kotlin Multiplatform).
            implementation(libs.kosherkotlin)
            // HTML mail, rendered by the platform's own browser engine.
            implementation(libs.composewebview)
            api(libs.compose.ui.tooling.preview)
            api(libs.compose.material3)
            implementation(libs.compose.material.icons.extended)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.structured.coroutines.annotations)
            // api: AppViewModel extends ViewModel and is used directly by desktopApp/androidApp.
            api(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime)
            implementation(libs.androidx.lifecycle.viewmodel.navigation3)
            implementation(libs.compose.nav3)
            implementation(libs.kotlinx.datetime)
            implementation(libs.materialKolor)
            implementation(libs.aboutlibraries.compose.m3)
            // The compose window's rich text (bold, lists, links) and its HTML.
            implementation(libs.richeditor)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.json)
            implementation(libs.sqlDelight.runtime)
            implementation(libs.sqlDelight.coroutines)
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }

        androidMain.dependencies {
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.activityCompose)
            implementation(libs.androidx.core)
            implementation(libs.androidx.work.runtime)
            implementation(libs.androidx.browser)
            implementation(libs.play.services.auth)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqlDelight.driver.android)
        }

        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            // The OS file dialog for attachments (native, not AWT's legacy one).
            implementation(libs.filekit.dialogs)
            implementation(libs.jna.platform)
            implementation(libs.sqlDelight.driver.sqlite)
            implementation(libs.sqlite.jdbc)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.nucleus.core.runtime)
            implementation(libs.nucleus.application)
            implementation(libs.nucleus.decorated.window.tao)
            implementation(libs.nucleus.system.color)
            implementation(libs.nucleus.native.http)
            implementation(libs.nucleus.native.http.ktor)
            implementation(libs.nucleus.updater.runtime)
            implementation(libs.nucleus.notification.common)
            implementation(libs.nucleus.autolaunch)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.ui.tooling)
}

sqldelight {
    databases {
        create("MailDatabase") {
            packageName.set("co.abaye.mailtice.db")
        }
    }
}

structuredCoroutines {
    useKmpCommonProfile()
}

compose.resources {
    // Independent of rootProject.name - renaming the app must not move Res.
    packageOfResClass = "mailtice.shared.generated.resources"
    // The platform modules host the window / tray / notifications, so they need the drawables too.
    publicResClass = true
}

val stabilityConfig = rootProject.layout.projectDirectory.file("config/stability-config.conf")

composeCompiler {
    stabilityConfigurationFiles.add(stabilityConfig)
}

aboutLibraries {
    export {
        outputFile = file("src/commonMain/composeResources/files/aboutlibraries.json")
    }
    library {
        duplicationMode = com.mikepenz.aboutlibraries.plugin.DuplicateMode.MERGE
    }
}

/**
 * Compose Resources on Android compares `values-*` against Locale.getLanguage(), which still answers
 * "iw" for Hebrew there (and "ji" for Yiddish on older versions). Publish those bundles a second time
 * under the old codes; generated, not committed, so each translation keeps a single source.
 */
val mirrorHebrewStringsForAndroid = tasks.register<Copy>("mirrorHebrewStringsForAndroid") {
    val resources = layout.projectDirectory.dir("src/commonMain/composeResources")
    from(resources.dir("values-he"))
    into(resources.dir("values-iw"))
}

val mirrorYiddishStringsForAndroid = tasks.register<Copy>("mirrorYiddishStringsForAndroid") {
    val resources = layout.projectDirectory.dir("src/commonMain/composeResources")
    from(resources.dir("values-yi"))
    into(resources.dir("values-ji"))
}

tasks.matching { it.name.endsWith("ForCommonMain") }.configureEach {
    dependsOn(mirrorHebrewStringsForAndroid, mirrorYiddishStringsForAndroid)
}

tasks.matching {
    it.name.startsWith("generateResourceAccessorsForCommonMain") ||
        it.name.startsWith("copyNonXmlValueResourcesForCommonMain") ||
        it.name.startsWith("prepareComposeResourcesTaskForCommonMain")
}.configureEach {
    dependsOn("exportLibraryDefinitions")
}

composeStabilityAnalyzer {
    stabilityConfigurationFiles.add(stabilityConfig)
    traceAll {
        enabled.set(providers.gradleProperty("composeTraceAll").map(String::toBoolean).orElse(false))
        threshold.set(2)
        variants.set(listOf("debug"))
    }
    stabilityValidation {
        enabled.set(true)
        outputDir.set(layout.projectDirectory.dir("stability"))
        includeTests.set(false)
        failOnStabilityChange.set(false)
    }
}
